### ISSUE TITLE
Using twitter bootstrap ?

### ISSUE THREAD

**Issue by jimlee2** [q2amarket/FlatBox#12]
Is it possible to use twitter bootstrap for the responsive section ? that way you dont have to hard code all those media queries?

**Comment by q2amarket** [comment]
@jimlee2 
Twitter bootstrap use own markup and class. Question2Answer has all inline HTML with PHP so it make difficult to change markup or even class.

This is why, we have to user Q2A core class and write css. I point out this topic many time but since entire system's markup is inline, it will take good amount of time.
